server:
  port: 8080
logging:
  level:
    fly: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.apache.coyote.http11.Http11InputBuffer: DEBUG
    org.springframework.web.client: DEBUG