spring:
  application:
    name: wethura-spring-demo
  security:
    user:
      name: wethura
      password: 111111
server:
  servlet:
    context-path: ${CONTEXT_PATH:/demo}
  port: 8080
logging:
  level:
    root: debug

call:
  endpoint: ${CALL_ENDPOINT:http://localhost:8080/demo/hello/permit}